import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./UI/Nav";
import { cookies } from "next/headers";
import UpdateSession from "./UpdateSession";
import { getSessionInfo } from "./lib/authentication";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Node UTStats Lite",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

	const cookieStore = cookies();

	const username = cookieStore.get("nstats_name")?.value ?? null;
	const sid = cookieStore.get("nstats_sid")?.value ?? null;
	const userId = cookieStore.get("nstats_userid")?.value ?? null;

	//const bValidSession = await bSessionValid("userId", "sessionId");

	//console.log(`bValidSession = ${bValidSession}`);

	const sessionInfo = await getSessionInfo(userId, sid);

	//const {bAdmin, error} = await bSessionAdminUser();

	//console.log("bAdmin, error");
	//console.log(bAdmin, error);

	//console.log(`userName = ${username}`);

	
	return (
		<html lang="en">
		<body className={inter.className}>
			<UpdateSession />
			<Nav sessionInfo={sessionInfo} bAdmin={true}/>
			<div className="padding-top"></div>
			{children}
			<footer>Horse Noise</footer>
		</body>
		</html>
	);
}
